DROP TABLE IF EXISTS `pfx_samples`;
CREATE TABLE `pfx_samples` (
`project_code` varchar(64) NULL default NULL,
`id` bigint(20) NULL default NULL,
`ox_code` varchar(64) NULL default NULL,
`source_code` varchar(64) NULL default NULL,
`sra_accession` varchar(64) NULL default NULL,
`cross_name` varchar(64) NULL default NULL,
`run` varchar(64) NULL default NULL,
`Instrument_Model` varchar(64) NULL default NULL,
`Library_Name` varchar(64) NULL default NULL,
`Run_Read_Count` varchar(64) NULL default NULL,
`Run_Base_Count` varchar(64) NULL default NULL,
`total` varchar(64) NULL default NULL,
`percent_mapped` decimal(5,2) NULL default NULL,
`percent_properly_paired` decimal(5,2) NULL default NULL,
`percent_singletons` decimal(5,2) NULL default NULL,
`percent_mate_other_chr` decimal(5,2) NULL default NULL,
`percent_duplicates` decimal(5,2) NULL default NULL,
`coverage` varchar(64) NULL default NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;